#!/usr/bin/env bash

# Script Root Directory
readonly ROOT_DIR=$(command cd -- "$(command dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && command pwd)

# Start AnnexFS Program
command python3 ${ROOT_DIR}/src/main.py "${@}"
